#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "${ACTIONS_TOOLKIT_DEBUG:-}" == "true" ]]; then
  set -x
fi

if (($# == 0)); then
  exec cat - >> "$GITHUB_STEP_SUMMARY"
else
  exec echo "$*" >> "$GITHUB_STEP_SUMMARY"
fi
