#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "${ACTIONS_TOOLKIT_DEBUG:-}" == "true" ]]; then
  set -x
fi

export GH_COMMAND_NAME="error"

if [[ -n "${file:-}" ]]; then
  export file___GH_PROPERTIES="$file"
fi

if [[ -n "${line:-}" ]]; then
  export line___GH_PROPERTIES="$line"
fi

if [[ -n "${col:-}" ]]; then
  export col___GH_PROPERTIES="$col"
fi

if (($# == 0)); then
  exec cat - | gh_actions_command
else
  exec gh_actions_command <<< "$*"
fi
