#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "${ACTIONS_TOOLKIT_DEBUG:-}" == "true" ]]; then
  set -x
fi

export GH_COMMAND_NAME="add-mask"

# Including EOL at EOF may cause unexpected unmasking
unset INCLUDE_EOL_AT_EOF

if (($# == 0)); then
  exec cat - | gh_actions_command
else
  echo -n "$*" | exec gh_actions_command
fi
