#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "${ACTIONS_TOOLKIT_DEBUG:-}" == "true" ]]; then
  set -x
fi

if (($# < 1)); then
  exec log-debug "$0 requires 1st argument that is the output name"
fi

readonly name="$1"; shift 1

echo "$name<<___ACTIONS_TOOLKIT_DELIMITER" >> "$GITHUB_OUTPUT"

if (($# == 0)); then
  cat - >> "$GITHUB_OUTPUT"
  echo >> "$GITHUB_OUTPUT"
else
  echo -n "$*" >> "$GITHUB_OUTPUT"
  echo >> "$GITHUB_OUTPUT"
fi

echo "___ACTIONS_TOOLKIT_DELIMITER" >> "$GITHUB_OUTPUT"
