#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "${ACTIONS_TOOLKIT_DEBUG:-}" == "true" ]]; then
  set -x
fi

export GH_COMMAND_NAME="stop-commands"

if (($# == 0)); then
  exec cat - | gh_actions_command
else
  exec gh_actions_command <<< "$*"
fi
