name: 'test set-env command'
on:
  pull_request:
    types: ['opened', 'synchronize', 'ready_for_review']
    paths:
      - '.github/workflows/test-set-env.yml'
      - 'src/set-env'
      - 'fixtures/*'

jobs:
  set-env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      ACTIONS_TOOLKIT_DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - run: echo "$PWD/src" >> $GITHUB_PATH
      - id: actions-core
        uses: ./.github/actions/actions-core-behavior
        with:
          single_line_file_path: ${{ github.workspace }}/fixtures/single-line.txt
          single_line_wo_newline_file_path: ${{ github.workspace }}/fixtures/single-line-wo-newline.txt
          multiple_lines_file_path: ${{ github.workspace }}/fixtures/multiple-lines.txt
          multiple_lines_wo_newline_file_path: ${{ github.workspace }}/fixtures/multiple-lines-wo-newline.txt
      - run: |
          set-env "argument-single-line" "$(cat fixtures/single-line.txt)"
          cat fixtures/single-line.txt | set-env "pipe-single-line"

          set-env "argument-single-line-wo-newline" "$(cat fixtures/single-line-wo-newline.txt)"
          cat fixtures/single-line-wo-newline.txt | set-env "pipe-single-line-wo-newline"

          set-env "argument-multiple-lines" "$(cat fixtures/multiple-lines.txt)"
          cat fixtures/multiple-lines.txt | set-env "pipe-multiple-lines"

          set-env "argument-multiple-lines-wo-newline" "$(cat fixtures/multiple-lines-wo-newline.txt)"
          cat fixtures/multiple-lines-wo-newline.txt | set-env "pipe-multiple-lines-wo-newline"
      - name: single-line
        id: single-line
        run: |
          if [[ "$(echo -n "${{ env.single-line }}")" == "${{ env.argument-single-line }}" ]]; then
            echo "argument-single-line works"
          else
            echo "::error::argument-single-line case seems to be broken"
            status=1
          fi

          if [[ "${{ env.single-line }}" == "${{ env.pipe-single-line }}" ]]; then
            echo "pipe-single-line works"
          else
            echo "::error::pipe-single-line case seems to be broken"
            status=1
          fi

          echo "::set-output name=status::${status:-0}"
      - name: single-line-wo-newline
        id: single-line-wo-newline
        run: |
          if [[ "${{ env.single-line-wo-newline }}" == "${{ env.argument-single-line-wo-newline }}" ]]; then
            echo "argument-single-line-wo-newline works"
          else
            echo "::error::argument-single-line-wo-newline case seems to be broken"
            status=1
          fi

          if [[ "${{ env.single-line-wo-newline }}" == "${{ env.pipe-single-line-wo-newline }}" ]]; then
            echo "pipe-single-line-wo-newline works"
          else
            echo "::error::pipe-single-line-wo-newline case seems to be broken"
            status=1
          fi

          echo "::set-output name=status::${status:-0}"
      - name: multiple-lines
        id: multiple-lines
        run: |
          if [[ "$(echo -n "${{ env.multiple-lines }}")" == "${{ env.argument-multiple-lines }}" ]]; then
            echo "argument-multiple-lines works"
          else
            echo "::error::argument-multiple-lines case seems to be broken"
            status=1
          fi

          if [[ "${{ env.multiple-lines }}" == "${{ env.pipe-multiple-lines }}" ]]; then
            echo "pipe-multiple-lines works"
          else
            echo "::error::pipe-multiple-lines case seems to be broken"
            status=1
          fi

          echo "::set-output name=status::${status:-0}"
      - name: multiple-lines-wo-newline
        id: multiple-lines-wo-newline
        run: |
          if [[ "${{ env.multiple-lines-wo-newline }}" == "${{ env.argument-multiple-lines-wo-newline }}" ]]; then
            echo "argument-multiple-lines-wo-newline works"
          else
            echo "::error::argument-multiple-lines-wo-newline case seems to be broken"
            status=1
          fi

          if [[ "${{ env.multiple-lines-wo-newline }}" == "${{ env.pipe-multiple-lines-wo-newline }}" ]]; then
            echo "pipe-multiple-lines-wo-newline works"
          else
            echo "::error::pipe-multiple-lines-wo-newline case seems to be broken"
            status=1
          fi
          
          echo "::set-output name=status::${status:-0}"
      - run: |
          if ((${{ steps.single-line.outputs.status }} + ${{ steps.single-line-wo-newline.outputs.status }} + ${{ steps.multiple-lines.outputs.status }} + ${{ steps.multiple-lines-wo-newline.outputs.status }})); then
            exit 1
          fi
        shell: bash
