name: 'test set-secret command'
on:
  push:
    branches:
      - main
    tags:
      - \d+.\d+.\d+
  pull_request:
    types: ['opened', 'synchronize', 'ready_for_review']
    paths:
      - '.github/workflows/test-set-secret.yml'
      - 'src/set-secret'
      - 'src/gh_actions_command'

jobs:
  set-secret:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      ACTIONS_TOOLKIT_DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - run: echo "$PWD/src" >> $GITHUB_PATH
      - run: |
          set-secret "Argument"
          echo "SingleLine" | set-secret
      - run: echo "Argument and SingleLine should be masked"
      - run: |
          set-secret "Contains Space"
          set-secret Not quate-ed
          echo "Line Includes Space" | set-secret
      - run: |
          echo "Contains Space should be masked"
          echo "Not quate-ed should be masked"
          echo "Line Includes Space should be masked"
          cat<<EOF
          Below should be visible
          Contains
          Space
          Not
          quate-ed
          Line
          Includes
          EOF
      - run: |
          # unquoted ver. is not neccessary to test because it's just an unexpected command.
          set-secret "$(cat fixtures/multiple-lines.txt)"
          cat fixtures/multiple-lines-wo-newline.txt | set-secret
      - run: |
          echo "Below should be masked"
          cat fixtures/multiple-lines.txt fixtures/multiple-lines-wo-newline.txt
          echo "Below should be visible"
          cat<<EOF
          End
          With
          Dirty
          EOL
          \tTwo or More
          Lines
          EOF
