version: 1
save_dir: .transart
source:
  locations:
  - path: .
    type: local
destination:
  location:
    api-token-name: GITHUB_TOKEN
    reponame: actions-toolkit-bash
    type: github-release
    username: jmatsu
    strategy: create
